name: Build and deploy snapshots

on:
  push:
    branches: [ main, 4.0.x, 3.2.x, 3.1.x, 'issue/**' ]

permissions: read-all

jobs:
  build:
    name: Build and deploy snapshots
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Java and Maven
        uses: spring-projects/spring-data-build/actions/setup-maven@4.0.x
        with:
          java-version: 'main'
          develocity-access-key: '${{ secrets.DEVELOCITY_ACCESS_KEY }}'
      - name: Install and Start Vault
        uses: ./.github/actions/setup-vault
      - name: Capture version
        run: |
          echo "PROJECT_VERSION=$(./ci/get-version.sh)" >> $GITHUB_ENV
      - name: Deploy to Artifactory
        if: ${{ github.repository_owner == 'spring-projects' && contains(env.PROJECT_VERSION, '-SNAPSHOT') }}
        uses: spring-projects/spring-data-build/actions/maven-artifactory-deploy@4.0.x
        with:
          build-name: 'spring-vault'
          skip-tests: 'false'
          username: '${{ secrets.ARTIFACTORY_USERNAME }}'
          password: '${{ secrets.ARTIFACTORY_PASSWORD }}'
